//Easy to change text in one place.
export default {
  appName: 'Zuvy',
  welcomeMessage: 'Welcome to Agentic AI Kirana!',
  CustomCarousel: {
    welcomeTitle: 'Welcome to Your Agentic AI Kirana',
    welcomeSubtext: 'Get more with Agentic AI Kirana',
    organizeTasksTitle: 'Organize Your Tasks Easily and Effectively',
    organizeTasksSubtext: 'Earn, Learn and Manage your business',
    stayOnTrackTitle: 'Stay on Track and Never Miss money',
    stayOnTrackSubtext:
      'Set reminders, track progress, and celebrate every milestone',
  },
  Profile: {
    name: 'Anjali Singh',
    position: 'Distributer',
    PersonalInfoTitle: 'Personal Information',
    edit: 'Edit',
    fullname: 'Full Name',
    role: 'Role',
    Zone: 'Zone',
    contact: 'Contact',
    Details: 'Details',
    setting: 'Settings',
    lang: 'Language',
    noti: 'Notifications',
    privaSecurity: 'Privacy & Security',
    logout: 'Logout',
  },
  ZuvyDashBoard: {
    welcomeTitle: 'Welcome back, Sarah 👋',
    overview: "Here's an overview of your Zuvy QR journey.",
    city: 'City: Mumbai',
    distriduteID: 'Distributor ID: ZUVY-12345',
    QRsummary: 'Your QR Kit Summary',
    QRpurchased: 'QRs Purchased',
    activekit: 'Active Kits',
    date: 'Guarantee Date',
    activationDate: "Your city's activation guarantee: ",
    refund: 'Refund Eligibility',
    refunddate: 'Eligible after 15/01/2025',
    viewKit: 'View My Kits',
    Distributor_Exp: 'Distributor Experiences',
    viewAll: 'View All',
    testimonialLabel: 'Hear from real Zuvy distributors',
    moreTestimonial: 'Watch more Testimonials',
    trustZuvylable: 'Why Distributors Trust Zuvy',
    verifyOwner: 'Verified QR Ownership',
    legalkit: 'Every kit you buy is legally',
    registerName: 'registered to your name.',
    commingSoon: 'Coming Soon',
    customerSuport: 'Contact Support',
    legalZuvy: 'Legal & About Zuvy',
  },
  ZuvyQrEdit: {
    H1: 'Edit zQR Details',
    zQR_ID: 'zQR ID : ',
    qrlabel1:
      'You can update basic details for your QR kit. \nOwnership and payment details are read-only.',
    basicsDetails: 'Basic Details',
    kitname: 'Kit Name',
    location: 'Location',
    Description: 'Description',
    Category: 'Category',
    contactInfo: 'Contact Information',
    emergencyContact: 'Emergency Contact',
    Email: 'Email',
    readOnlyinfo: 'Read-Only Information',
    Owner: 'Owner',
    Purchase_Date: 'Purchase Date',
    Payment_Method: 'Payment Method',
    Amount_Paid: 'Amount Paid',
    Security: 'Security',
    downloadQr: 'Download QR Code',
    share: 'Share',
  },
};
